### ISSUE TITLE
Spy/stub context functions by default

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/kap-plugin-test#1]
I'm wondering if it would be better if we provided spies/stubs for the context functions by default. This could simplify the tests because we don't have to spie/stub all the functions anymore. The usage example would then look like this:

```js
import test from 'ava';
import kapPluginTest from 'kap-plugin-test';
import myPlugin from '.';

test(async t => {
	const service = kapPluginTest(myPlugin);

	const plugin = service('path/to/input.gif', {
		config: {
			apiKey: 'a3b78f9ce6'
		}
	});

	await plugin.exec();

	t.true(plugin.context.copyToClipboard.calledWith('http://gph.is/1TGDci8'));
});
```

Because every test has it's own test mock context object, the different spies/stubs wouldn't interfer.

// @sindresorhus @kevva

**Comment by sindresorhus** [comment]
Yes. I like it a lot.

**Comment by sindresorhus** [comment]
Unrelated, but I would name it `plugin.run()` instead of `plugin.exec()`.

**Comment by SamVerschueren** [comment]
> Unrelated, but I would name it plugin.run() instead of plugin.exec()

Good idea, sounds better!

**Comment by kevva** [comment]
You have my upvote too. Anything that reduces complexity :).
