### ISSUE TITLE
Remove the need to pass in module to the main function

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/kap-plugin-test#3]
Currently you need to pass the plugin module to the main function as documented [here](https://github.com/SamVerschueren/kap-plugin-test#kapplugintestmodule).

```js
import kapPluginTest from 'kap-plugin-test';
import myPlugin from '.';

const service = kapPluginTest(myPlugin);
```

It would be better to just auto-detect the main file (which is always `index.js` right? @sindresorhus) so that we can make it cleaner.

```js
import kapPluginTest from 'kap-plugin-test';

const service = kapPluginTest();
```

We can use [read-pkg-up](https://github.com/sindresorhus/read-pkg-up) to find the main `package.json` and use that file path to grab the correct `index.js` file.

**Comment by sindresorhus** [comment]
> We can use read-pkg-up to find the main package.json and use that file path to grab the correct index.js file.

No need for that. You can just use `require-from`, which uses the Node.js require algorithm.

**Comment by sindresorhus** [comment]
And yes, agree with making it as little code as possible.

**Comment by SamVerschueren** [comment]
> No need for that. You can just use require-from, which uses the Node.js require algorithm.

Would that work? I mean, the test file is not always in the root of the project. So using `require-from` with `process.cwd()` as the path wouldn't always work.

**Comment by SamVerschueren** [comment]
@sindresorhus Care to elaborate on the `require-from` method? Would it be possible to use that without `read-pkg-up` or with a combination of both?
