### ISSUE TITLE
Support multiple shared services

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/kap-plugin-test#4]
The plugin `shareServices` export is an array of services. Currently, `kap-plugin-test` always [takes the first one](https://github.com/SamVerschueren/kap-plugin-test/blob/master/index.js#L24). I think we should also support selecting other services.

I was thinking about a `service` option which accepts the index of the service and is `0` by default.

// @sindresorhus @kevva

**Comment by sindresorhus** [comment]
> I was thinking about a service option which accepts the index of the service and is 0 by default.

👍
